"""Generated by atdpy from type definitions in task_output.atd.

This implements classes for the types defined in 'task_output.atd', providing
methods and functions to convert data from/to JSON.
"""

# Disable flake8 entirely on this file:
# flake8: noqa

# Import annotations to allow forward references
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, NoReturn, Optional, Tuple, Union

import json

############################################################################
# Private functions
############################################################################


def _atd_missing_json_field(type_name: str, json_field_name: str) -> NoReturn:
    raise ValueError(f"missing field '{json_field_name}'"
                     f" in JSON object of type '{type_name}'")


def _atd_bad_json(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible JSON value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_bad_python(expected_type: str, json_value: Any) -> NoReturn:
    value_str = str(json_value)
    if len(value_str) > 200:
        value_str = value_str[:200] + '…'

    raise ValueError(f"incompatible Python value where"
                     f" type '{expected_type}' was expected: '{value_str}'")


def _atd_read_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_json('unit', x)


def _atd_read_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_json('bool', x)


def _atd_read_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_json('int', x)


def _atd_read_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_json('float', x)


def _atd_read_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_json('str', x)


def _atd_read_list(
            read_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def read_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [read_elt(elt) for elt in elts]
        else:
            _atd_bad_json('array', elts)
    return read_list


def _atd_read_assoc_array_into_dict(
            read_key: Callable[[Any], Any],
            read_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[Any, Any]]:
    def read_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {read_key(elt[0]): read_value(elt[1]) for elt in elts}
        else:
            _atd_bad_json('array', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_dict(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def read_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_read_string(k): read_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_assoc_object_into_list(
            read_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], List[Tuple[str, Any]]]:
    def read_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(_atd_read_string(k), read_value(v))
                    for k, v in elts.items()]
        else:
            _atd_bad_json('object', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return read_assoc


def _atd_read_nullable(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return read_elt(x)
    return read_nullable


def _atd_read_option(read_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def read_option(x: Any) -> Any:
        if x == 'None':
            return None
        elif isinstance(x, List) and len(x) == 2 and x[0] == 'Some':
            return read_elt(x[1])
        else:
            _atd_bad_json('option', x)
            raise AssertionError('impossible')  # keep mypy happy
    return read_option


def _atd_write_unit(x: Any) -> None:
    if x is None:
        return x
    else:
        _atd_bad_python('unit', x)


def _atd_write_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    else:
        _atd_bad_python('bool', x)


def _atd_write_int(x: Any) -> int:
    if isinstance(x, int):
        return x
    else:
        _atd_bad_python('int', x)


def _atd_write_float(x: Any) -> float:
    if isinstance(x, (int, float)):
        return x
    else:
        _atd_bad_python('float', x)


def _atd_write_string(x: Any) -> str:
    if isinstance(x, str):
        return x
    else:
        _atd_bad_python('str', x)


def _atd_write_list(
            write_elt: Callable[[Any], Any]
        ) -> Callable[[List[Any]], List[Any]]:
    def write_list(elts: List[Any]) -> List[Any]:
        if isinstance(elts, list):
            return [write_elt(elt) for elt in elts]
        else:
            _atd_bad_python('list', elts)
    return write_list


def _atd_write_assoc_dict_to_array(
            write_key: Callable[[Any], Any],
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[Any, Any]], List[Tuple[Any, Any]]]:
    def write_assoc(elts: Dict[str, Any]) -> List[Tuple[str, Any]]:
        if isinstance(elts, dict):
            return [(write_key(k), write_value(v)) for k, v in elts.items()]
        else:
            _atd_bad_python('Dict[str, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_dict_to_object(
            write_value: Callable[[Any], Any]
        ) -> Callable[[Dict[str, Any]], Dict[str, Any]]:
    def write_assoc(elts: Dict[str, Any]) -> Dict[str, Any]:
        if isinstance(elts, dict):
            return {_atd_write_string(k): write_value(v)
                    for k, v in elts.items()}
        else:
            _atd_bad_python('Dict[str, <value type>]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_assoc_list_to_object(
            write_value: Callable[[Any], Any],
        ) -> Callable[[List[Any]], Dict[str, Any]]:
    def write_assoc(elts: List[List[Any]]) -> Dict[str, Any]:
        if isinstance(elts, list):
            return {_atd_write_string(elt[0]): write_value(elt[1])
                    for elt in elts}
        else:
            _atd_bad_python('List[Tuple[<key type>, <value type>]]', elts)
            raise AssertionError('impossible')  # keep mypy happy
    return write_assoc


def _atd_write_nullable(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_nullable(x: Any) -> Any:
        if x is None:
            return None
        else:
            return write_elt(x)
    return write_nullable


def _atd_write_option(write_elt: Callable[[Any], Any]) \
        -> Callable[[Optional[Any]], Optional[Any]]:
    def write_option(x: Any) -> Any:
        if x is None:
            return 'None'
        else:
            return ['Some', write_elt(x)]
    return write_option


############################################################################
# Public classes
############################################################################


@dataclass
class TokenCounts:
    """Original type: token_counts = { ... }"""

    input_tokens: int = field(default_factory=lambda: 0)
    output_tokens: int = field(default_factory=lambda: 0)
    total_tokens: int = field(default_factory=lambda: 0)

    @classmethod
    def from_json(cls, x: Any) -> 'TokenCounts':
        if isinstance(x, dict):
            return cls(
                input_tokens=_atd_read_int(x['input_tokens']) if 'input_tokens' in x else 0,
                output_tokens=_atd_read_int(x['output_tokens']) if 'output_tokens' in x else 0,
                total_tokens=_atd_read_int(x['total_tokens']) if 'total_tokens' in x else 0,
            )
        else:
            _atd_bad_json('TokenCounts', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['input_tokens'] = _atd_write_int(self.input_tokens)
        res['output_tokens'] = _atd_write_int(self.output_tokens)
        res['total_tokens'] = _atd_write_int(self.total_tokens)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'TokenCounts':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Success:
    """Original type: task_status = [ ... | Success | ... ]"""

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Success'

    @staticmethod
    def to_json() -> Any:
        return 'Success'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Failure:
    """Original type: task_status = [ ... | Failure | ... ]"""

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Failure'

    @staticmethod
    def to_json() -> Any:
        return 'Failure'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class TaskStatus:
    """Original type: task_status = [ ... ]"""

    value: Union[Success, Failure]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'TaskStatus':
        if isinstance(x, str):
            if x == 'Success':
                return cls(Success())
            if x == 'Failure':
                return cls(Failure())
            _atd_bad_json('TaskStatus', x)
        _atd_bad_json('TaskStatus', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'TaskStatus':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FullProofTask:
    """Original type: task_kind = [ ... | FullProofTask | ... ]"""

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'FullProofTask'

    @staticmethod
    def to_json() -> Any:
        return 'FullProofTask'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class OtherTask:
    """Original type: task_kind = [ ... | OtherTask of ... | ... ]"""

    value: str

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'OtherTask'

    def to_json(self) -> Any:
        return ['OtherTask', _atd_write_string(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class TaskKind:
    """Original type: task_kind = [ ... ]"""

    value: Union[FullProofTask, OtherTask]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'TaskKind':
        if isinstance(x, str):
            if x == 'FullProofTask':
                return cls(FullProofTask())
            _atd_bad_json('TaskKind', x)
        if isinstance(x, List) and len(x) == 2:
            cons = x[0]
            if cons == 'OtherTask':
                return cls(OtherTask(_atd_read_string(x[1])))
            _atd_bad_json('TaskKind', x)
        _atd_bad_json('TaskKind', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'TaskKind':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResourceUsage:
    """Original type: resource_usage = { ... }"""

    execution_time_sec: float = field(default_factory=lambda: 0.0)
    cpu_time_sec: float = field(default_factory=lambda: 0.0)
    gpu_time_sec: float = field(default_factory=lambda: 0.0)

    @classmethod
    def from_json(cls, x: Any) -> 'ResourceUsage':
        if isinstance(x, dict):
            return cls(
                execution_time_sec=_atd_read_float(x['execution_time_sec']) if 'execution_time_sec' in x else 0.0,
                cpu_time_sec=_atd_read_float(x['cpu_time_sec']) if 'cpu_time_sec' in x else 0.0,
                gpu_time_sec=_atd_read_float(x['gpu_time_sec']) if 'gpu_time_sec' in x else 0.0,
            )
        else:
            _atd_bad_json('ResourceUsage', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['execution_time_sec'] = _atd_write_float(self.execution_time_sec)
        res['cpu_time_sec'] = _atd_write_float(self.cpu_time_sec)
        res['gpu_time_sec'] = _atd_write_float(self.gpu_time_sec)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'ResourceUsage':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Timeout:
    """Original type: resource_exhaustion_kind = [ ... | Timeout of ... | ... ]"""

    value: int

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Timeout'

    def to_json(self) -> Any:
        return ['Timeout', _atd_write_int(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class MaxLLMCalls:
    """Original type: resource_exhaustion_kind = [ ... | MaxLLMCalls of ... | ... ]"""

    value: int

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'MaxLLMCalls'

    def to_json(self) -> Any:
        return ['MaxLLMCalls', _atd_write_int(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResourceExhaustionKind:
    """Original type: resource_exhaustion_kind = [ ... ]"""

    value: Union[Timeout, MaxLLMCalls]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'ResourceExhaustionKind':
        if isinstance(x, List) and len(x) == 2:
            cons = x[0]
            if cons == 'Timeout':
                return cls(Timeout(_atd_read_int(x[1])))
            if cons == 'MaxLLMCalls':
                return cls(MaxLLMCalls(_atd_read_int(x[1])))
            _atd_bad_json('ResourceExhaustionKind', x)
        _atd_bad_json('ResourceExhaustionKind', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'ResourceExhaustionKind':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Metrics:
    """Original type: metrics = { ... }"""

    llm_invocation_count: int = field(default_factory=lambda: 0)
    token_counts: TokenCounts = field(default_factory=lambda: TokenCounts())
    resource_usage: ResourceUsage = field(default_factory=lambda: ResourceUsage())
    custom: Any = field(default_factory=lambda: None)

    @classmethod
    def from_json(cls, x: Any) -> 'Metrics':
        if isinstance(x, dict):
            return cls(
                llm_invocation_count=_atd_read_int(x['llm_invocation_count']) if 'llm_invocation_count' in x else 0,
                token_counts=TokenCounts.from_json(x['token_counts']) if 'token_counts' in x else TokenCounts(),
                resource_usage=ResourceUsage.from_json(x['resource_usage']) if 'resource_usage' in x else ResourceUsage(),
                custom=(lambda x: x)(x['custom']) if 'custom' in x else None,
            )
        else:
            _atd_bad_json('Metrics', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['llm_invocation_count'] = _atd_write_int(self.llm_invocation_count)
        res['token_counts'] = (lambda x: x.to_json())(self.token_counts)
        res['resource_usage'] = (lambda x: x.to_json())(self.resource_usage)
        res['custom'] = (lambda x: x)(self.custom)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'Metrics':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ResourceExhaustion:
    """Original type: failure_reason = [ ... | ResourceExhaustion of ... | ... ]"""

    value: ResourceExhaustionKind

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'ResourceExhaustion'

    def to_json(self) -> Any:
        return ['ResourceExhaustion', (lambda x: x.to_json())(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class ExecutionError:
    """Original type: failure_reason = [ ... | ExecutionError of ... | ... ]"""

    value: str

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'ExecutionError'

    def to_json(self) -> Any:
        return ['ExecutionError', _atd_write_string(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class Other:
    """Original type: failure_reason = [ ... | Other of ... | ... ]"""

    value: str

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Other'

    def to_json(self) -> Any:
        return ['Other', _atd_write_string(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class FailureReason:
    """Original type: failure_reason = [ ... ]"""

    value: Union[ResourceExhaustion, ExecutionError, Other]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'FailureReason':
        if isinstance(x, List) and len(x) == 2:
            cons = x[0]
            if cons == 'ResourceExhaustion':
                return cls(ResourceExhaustion(ResourceExhaustionKind.from_json(x[1])))
            if cons == 'ExecutionError':
                return cls(ExecutionError(_atd_read_string(x[1])))
            if cons == 'Other':
                return cls(Other(_atd_read_string(x[1])))
            _atd_bad_json('FailureReason', x)
        _atd_bad_json('FailureReason', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'FailureReason':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


@dataclass
class TaskOutput:
    """Original type: task_output = { ... }"""

    run_id: str
    task_kind: TaskKind
    task_id: str
    timestamp_utc: str
    agent_name: str
    status: TaskStatus
    metrics: Metrics
    trace_id: Optional[str] = None
    failure_reason: Optional[FailureReason] = None
    results: Any = field(default_factory=lambda: None)

    @classmethod
    def from_json(cls, x: Any) -> 'TaskOutput':
        if isinstance(x, dict):
            return cls(
                run_id=_atd_read_string(x['run_id']) if 'run_id' in x else _atd_missing_json_field('TaskOutput', 'run_id'),
                task_kind=TaskKind.from_json(x['task_kind']) if 'task_kind' in x else _atd_missing_json_field('TaskOutput', 'task_kind'),
                task_id=_atd_read_string(x['task_id']) if 'task_id' in x else _atd_missing_json_field('TaskOutput', 'task_id'),
                timestamp_utc=_atd_read_string(x['timestamp_utc']) if 'timestamp_utc' in x else _atd_missing_json_field('TaskOutput', 'timestamp_utc'),
                agent_name=_atd_read_string(x['agent_name']) if 'agent_name' in x else _atd_missing_json_field('TaskOutput', 'agent_name'),
                status=TaskStatus.from_json(x['status']) if 'status' in x else _atd_missing_json_field('TaskOutput', 'status'),
                metrics=Metrics.from_json(x['metrics']) if 'metrics' in x else _atd_missing_json_field('TaskOutput', 'metrics'),
                trace_id=_atd_read_string(x['trace_id']) if 'trace_id' in x else None,
                failure_reason=FailureReason.from_json(x['failure_reason']) if 'failure_reason' in x else None,
                results=(lambda x: x)(x['results']) if 'results' in x else None,
            )
        else:
            _atd_bad_json('TaskOutput', x)

    def to_json(self) -> Any:
        res: Dict[str, Any] = {}
        res['run_id'] = _atd_write_string(self.run_id)
        res['task_kind'] = (lambda x: x.to_json())(self.task_kind)
        res['task_id'] = _atd_write_string(self.task_id)
        res['timestamp_utc'] = _atd_write_string(self.timestamp_utc)
        res['agent_name'] = _atd_write_string(self.agent_name)
        res['status'] = (lambda x: x.to_json())(self.status)
        res['metrics'] = (lambda x: x.to_json())(self.metrics)
        if self.trace_id is not None:
            res['trace_id'] = _atd_write_string(self.trace_id)
        if self.failure_reason is not None:
            res['failure_reason'] = (lambda x: x.to_json())(self.failure_reason)
        res['results'] = (lambda x: x)(self.results)
        return res

    @classmethod
    def from_json_string(cls, x: str) -> 'TaskOutput':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)
