from typing import Protocol, TypeVar, List, Tuple, Optional, Any, Generator, Dict
from .types import BeamNode

T = TypeVar("T")

class Logger(Protocol):
    def log(self, event: str, **kwargs): ...

class LLMClient(Protocol):
    def generate(self, prompt: str, n: int) -> List[Tuple[str, float, str]]: ...

class StateT(Protocol):
    def get_goals(self) -> List[str]: ...
    def apply_tactic(self, tactic: str) -> Tuple[bool, List[str], Optional["StateT"], Optional[str]]: ...
    def format_prompt_context(self) -> Dict[str, Any]: ...

class Action(Protocol[T]):
    def interact(self, state: T) -> Tuple[bool, List[str], Optional[T], float]: ...
    def to_text(self) -> str: ...
    def get_metadata(self) -> Dict[str, Any]: ...

class Strategy(Protocol[T]):
    def rollout(self, node: BeamNode, state: T, n: int) -> Generator[Tuple[float, Action[T]], None, None]: ...

class Guidance(Protocol[T]):
    def score(self, state: T, node: BeamNode) -> Tuple[float, Dict[str, Any]]: ...